controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_joint
      - upperarm_joint
      - forearm_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper
initial:  # Define initial robot poses per group
  - group: arm
    pose: ready
  - group: gripper
    pose: open