arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - upperarm_joint
    - forearm_joint
  gains:
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upperarm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joint: gripper
