arm_velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - base_joint
    - shoulder_joint
    - elbow_joint
    - wrist_joint
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1