arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - upperarm_joint
    - forearm_joint
  gains:
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upperarm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

gripper_controller_top:
  type: position_controllers/GripperActionController
  joint: gripper_top_joint

gripper_controller_bottom:
  type: position_controllers/GripperActionController
  joint: gripper_bottom_joint
