controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_joint
      - upperarm_joint
      - forearm_joint
  - name: gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: True
    joints:
      - gripper