controller_list:
  - name: arm_simple_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
  - name: hand_simple_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - finger_joint